// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okhjqftggfnewvgivgku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9raGpxZnRnZ2ZuZXd2Z2l2Z2t1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MDA2ODksImV4cCI6MjA2Mzk3NjY4OX0.Vjqr72155aLA3nFxpsKqNr5IL1cwyWYD9Xn5vUPZlts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);